drop schema if exists  cascais  cascade;
create schema cascais;

--grant privileges
GRANT ALL ON SCHEMA cascais to dssg2017_admin;
grant all on schema cascais to hholmestad, tfilho, kyang;
CREATE TABLE municipe (
	id INTEGER NOT NULL, 
	"data_de_inserc~ao_de_dados" VARCHAR(19), 
	data_de_nasscimento VARCHAR(19), 
	idade INTEGER NOT NULL, 
	sexo VARCHAR(9), 
	"portador_de_defici^encia" VARCHAR(4), 
	"defici^encia" VARCHAR(163), 
	morada VARCHAR(255), 
	localidade VARCHAR(23), 
	cp VARCHAR(9), 
	freguesia VARCHAR(26), 
	nacionalidade VARCHAR(13), 
	naturalidade VARCHAR(36), 
	"possu'i_carta_de_conduc~ao" VARCHAR(8), 
	"autoriza_a_utilizac~ao_dos_seus_dados_pessoais_para_divulgac~ao_de_outras_iniciativas_da_dpre" VARCHAR(4), 
	"n~ao_autoriza_a_utilizac~ao_dos_seus_dados_pessoais_para_divulgac~ao_de_outras_iniciativas_da_dpre" VARCHAR(4), 
	"autoriza_a_disponibilizac~ao_dos_seus_dados_pessoais_`a_dgert_para_eventual_auscultac~ao_relativamente_`a_qualidade_dos_servicos_de_" VARCHAR(4), 
	"n~ao_autoriza_a_disponibilizac~ao_dos_seus_dados_pessoais_`a_dgert_para_eventual_auscultac~ao_relativamente_`a_qualidade_dos_servicos" VARCHAR(4), 
	"observac~oes" VARCHAR(261)
);

CREATE TABLE atendimento (
	id INTEGER NOT NULL, 
	"'ultima_data_de_atendimento" VARCHAR(10), 
	tipo_de_atendimento VARCHAR(10), 
	"informac~ao_sobre_a_dois" VARCHAR(4), 
	"informac~ao_sobre_epc" VARCHAR(4), 
	"informac~ao_sobre_gadi" VARCHAR(4), 
	"informac~ao_sobre_oficinas" VARCHAR(4), 
	"informac~ao_sobre_poj" VARCHAR(4), 
	"informac~ao_sobre_pvp" VARCHAR(4), 
	"informac~ao_sobre_virar" VARCHAR(32), 
	"informac~ao_sobre_outro" VARCHAR(4), 
	"informac~ao_sobre_outro___qual" VARCHAR(47), 
	"inscric~ao_em_a_dois" VARCHAR(32), 
	"inscric~ao_em_epc" VARCHAR(32), 
	"inscric~ao_em_gadi" VARCHAR(4), 
	"inscric~ao_em_oficinas" VARCHAR(4), 
	"inscric~ao_em_poj" VARCHAR(4), 
	"inscric~ao_em_virar" VARCHAR(32), 
	"inscric~ao_em_outro" VARCHAR(4), 
	"inscric~ao_em_outro___qual" VARCHAR(18), 
	"observac~oes" VARCHAR(86), 
	encaminhado_para_rota_jovem VARCHAR(4), 
	encaminhado_para_centro_de_emprego VARCHAR(4), 
	"encaminhado_para_cfr_de_alcoit~ao" VARCHAR(4), 
	gabinete_de_emprego_gaivotas_da_torre VARCHAR(4), 
	gabinete_de_emprego_sea_adroana VARCHAR(4), 
	gabinete_de_emprego_cercica VARCHAR(4), 
	gabinete_de_emprego_jf_do_estoril VARCHAR(4), 
	"gabinete_de_emprego_cruz_vermelha_/_parede" VARCHAR(4), 
	gabinete_de_emprego_ccp_carcavelos VARCHAR(4), 
	gabinete_de_emprego_centro_cultural_moldavo VARCHAR(32), 
	gabinete_de_emprego_cespa VARCHAR(32), 
	gabinete_de_emprego_diis_matocheironhos VARCHAR(32), 
	gabinete_de_emprego_diis_zambujal VARCHAR(32), 
	gabinete_de_emprego_loja_cascais_jovem VARCHAR(32), 
	gabinete_de_emprego_cqep VARCHAR(32), 
	servicos_de_apoio_ao_empreendedor_sea VARCHAR(4), 
	servicos_de_apoio_ao_empreendedor_dna VARCHAR(4), 
	servicos_de_apoio_ao_empreendedor_ccp_carcavelos VARCHAR(4), 
	servicos_de_apoio_ao_empreendedor_aecc VARCHAR(32), 
	servicos_de_apoio_ao_empreendedor_outros VARCHAR(4), 
	servicos_de_apoio_ao_empreendedor_outros___qual VARCHAR(29), 
	"t'ecnico/a_de_atendimento" VARCHAR(18)
);

CREATE TABLE gadi (
	id VARCHAR(58) NOT NULL, 
	"'ultima_data_de_atendimento_gadi" VARCHAR(102) NOT NULL, 
	"t'ecnico/a_gadi" VARCHAR(17), 
	no_de_minutos_de_acompanhamento VARCHAR(5), 
	"conte'udo_autoconhecimento" VARCHAR(16), 
	"conte'udo_locus_controlo_interno" VARCHAR(52), 
	"conte'udo_instrumentos_pae" VARCHAR(4), 
	"conte'udo_ativac~ao_de_recursos_externos" VARCHAR(4), 
	"conte'udo_outros" VARCHAR(4), 
	"conte'udo_outros___qual" VARCHAR(30), 
	utilidade_percebida VARCHAR(10), 
	"registo_da_sess~ao" VARCHAR(267), 
	"observac~oes" VARCHAR(261)
);

CREATE TABLE virar (
	id VARCHAR(24) NOT NULL, 
	"'ultima_data_de_atendimento_virar" VARCHAR(20), 
	"motivo_da_inscric~ao" VARCHAR(260), 
	data_de_entrada VARCHAR(26), 
	"data_de_sa'ida" VARCHAR(65), 
	"observac~oes" VARCHAR(82), 
	"motivo_de_sa'ida_trabalho" VARCHAR(4), 
	"motivo_de_sa'ida_formac~ao" VARCHAR(32), 
	"motivo_de_sa'ida_outro" VARCHAR(4), 
	"motivo_de_sa'ida_outro___qual" VARCHAR(31), 
	"sess~oes_participadas" VARCHAR(4), 
	utilidade_percebida VARCHAR(10), 
	grupo VARCHAR(7)
);

CREATE TABLE pvp (
	id INTEGER NOT NULL, 
	"'ultima_data_de_acompanhamento_pvp" VARCHAR(10), 
	data_de_entrada VARCHAR(10), 
	"data_de_t'ermino" VARCHAR(10), 
	servico_enquadrador VARCHAR(70), 
	"t'ecnico/a_enquadrador/a" VARCHAR(37), 
	telefone VARCHAR(32), 
	e_mail VARCHAR(32), 
	"func~oes" VARCHAR(54), 
	participou_nas_oficinas VARCHAR(4), 
	horas VARCHAR(32), 
	"acc~oes_realizadas" VARCHAR(4), 
	fim_do_contrato_cei VARCHAR(32), 
	"fim_do_sub'idio_de_desemprego" VARCHAR(32), 
	utilidade_percebida VARCHAR(9), 
	"sa'ida_do_programa" VARCHAR(22), 
	em VARCHAR(10), 
	outro_motivo VARCHAR(41), 
	"t'ecnico/a_de_acompanhamento" VARCHAR(17), 
	"conte'udo_autoconhecimento" VARCHAR(4), 
	"conte'udo_locus_controlo_interno" VARCHAR(4), 
	"conte'udo_instrumentos_pae" VARCHAR(4), 
	"conte'udo_ativac~ao_de_recursos_externos" VARCHAR(4), 
	"conte'udo_outro" VARCHAR(4), 
	"conte'udo_outro___qual" VARCHAR(29), 
	acompanhamento VARCHAR(4), 
	no_de_horas VARCHAR(4), 
	"registo_da_sess~ao" VARCHAR(262), 
	"observac~oes" VARCHAR(259)
);

CREATE TABLE mentoria (
	id VARCHAR(49) NOT NULL, 
	"'ultima_data_de_atendimento_mentoria" VARCHAR(10), 
	estado VARCHAR(39), 
	"experi^encia_profissional" VARCHAR(266), 
	"disponibilidade_de_hor'ario" VARCHAR(246), 
	objectivo_da_mentoria VARCHAR(264), 
	"perfil_do/a_mentor/a" VARCHAR(268), 
	particpou_em_programas_da_cmc VARCHAR(4), 
	qual VARCHAR(262), 
	conhecimento_do_programa VARCHAR(59), 
	no_de_encontros VARCHAR(4), 
	horas VARCHAR(4), 
	temas VARCHAR(32), 
	"compet^encias_desenvolvidas" VARCHAR(32), 
	acompanhamento VARCHAR(32), 
	"condic~oes_de_participac~ao___reside,_trabalha_ou_estuda_no_concelho_de_cascais" VARCHAR(4), 
	"condic~oes_de_participac~ao___leu_a_descric~ao_do_projeto_e_compreende_os_objetivos" VARCHAR(4), 
	"condic~oes_de_participac~ao___dispon'ivel_para_contatos_com_os_t'ecnicos/as_do_projeto" VARCHAR(4), 
	"certificado_do/a_mentorando/a_entregue" VARCHAR(32), 
	"certificado_do/a_mentorando/a_entregue_em" VARCHAR(32), 
	"certificado_do/a_mentor/a_entregue" VARCHAR(32), 
	"certificado_do/a_mentor/a_entregue_em" VARCHAR(32), 
	entrevista_na_dpre VARCHAR(32), 
	entrevista_na_dpre_em VARCHAR(32), 
	"entrevista_na_dpre_t'ecnico/a" VARCHAR(32), 
	"data_de_in'icio" VARCHAR(32), 
	data_de_fim VARCHAR(32), 
	utilidade_percebida VARCHAR(32), 
	"profiss~ao" VARCHAR(32), 
	"observac~oes" VARCHAR(32)
);

CREATE TABLE mentor (
	id INTEGER NOT NULL, 
	"'ultima_data_de_atendimento_mentor" VARCHAR(10), 
	"'area(s)_em_que_gostaria_de_ser_mentor/a" VARCHAR(255) NOT NULL, 
	disponibilidade VARCHAR(63) NOT NULL, 
	"motivac~ao" VARCHAR(260) NOT NULL, 
	participou_em_algum_programa_da_cmc VARCHAR(36), 
	conhecimento_do_programa VARCHAR(59), 
	certificado_mentor_entregue VARCHAR(37), 
	certificado_mentor_entregue_em VARCHAR(32), 
	"condic~oes_de_participac~ao___reside,_trabalha_ou_estuda_no_concelho_de_cascais" VARCHAR(4), 
	"condic~oes_de_participac~ao___leu_a_descric~ao_do_projeto_e_compreende_os_objetivos" VARCHAR(1) NOT NULL, 
	"condic~oes_de_participac~ao___dispon'ivel_para_contatos_com_os_t'ecnicos/as_do_projeto" VARCHAR(1) NOT NULL, 
	"observac~oes" VARCHAR(4)
);

CREATE TABLE epc (
	id INTEGER NOT NULL, 
	"'ultima_data_da_sess~ao" VARCHAR(10), 
	local VARCHAR(42), 
	"situac~ao" VARCHAR(8), 
	data_de_candidatura VARCHAR(10), 
	"medida_de_est'agio_a_que_se_candidata___medida_est'agios_emprego" VARCHAR(4), 
	"medida_de_est'agio_a_que_se_candidata___medida_reativar" VARCHAR(4), 
	"idade_entre_os_18_e_3_anos,_inclusive,_com_qualificac~ao_igual_ou_superior_ao_9o_ano_de_escolaridade" VARCHAR(4), 
	"idade_superior_a_3_anos,_com_qualificac~ao_obtida_h'a_menos_de_3_anos" VARCHAR(4), 
	"qualquer_idade_e_n'ivel_de_qualificac~ao_se_se_verificar_uma_das_seguintes_situac~oes" VARCHAR(4), 
	"refer^encia_da_vaga" VARCHAR(11), 
	entidade_empregadora VARCHAR(115), 
	registo_oficial VARCHAR(87), 
	"func~ao_de_est'agio" VARCHAR(131), 
	"convocado/a_para_entrevista_na_dpre" VARCHAR(4), 
	data_da_entrevista VARCHAR(10), 
	"t'ecnico/a_da_dpre" VARCHAR(17), 
	"selecionado/a" VARCHAR(4), 
	"n~ao_selecionado/a" VARCHAR(4), 
	"informado/a_do_desfecho_do_processo" VARCHAR(4), 
	em VARCHAR(10), 
	"est'agio_entidade_empregadora" VARCHAR(75), 
	nome_oficial VARCHAR(59), 
	localidade VARCHAR(18), 
	freguesia VARCHAR(21), 
	"'area_de_atividade" VARCHAR(46), 
	"t'ecnico/a_dpre" VARCHAR(17), 
	grupo VARCHAR(34), 
	"data_de_in'icio" VARCHAR(10), 
	data_de_fim VARCHAR(10), 
	"n'ivel_de_qualificac~ao" VARCHAR(7), 
	"'area_de_qualificac~ao" VARCHAR(44), 
	"func~ao" VARCHAR(70), 
	"situac~ao_do_est'agio" VARCHAR(41), 
	medida VARCHAR(21), 
	"durac~ao" VARCHAR(22), 
	"observac~oes" VARCHAR(265), 
	utilidade_percebida VARCHAR(9)
);

CREATE TABLE oficinas (
	id VARCHAR(56), 
	"'ultima_data_de_atendimento_oficinas" VARCHAR(10), 
	oficina_em_que_se_inscreve VARCHAR(36), 
	outra___qual VARCHAR(22), 
	"local_da_sess~ao" VARCHAR(39), 
	outro___qual VARCHAR(46), 
	"motivo(s)_da_inscric~ao" VARCHAR(262), 
	"sess~oes_/_horas_frequentadas" VARCHAR(37), 
	"faltou_(com_justificac~ao)" VARCHAR(32), 
	"justificac~ao" VARCHAR(32), 
	"faltou_(sem_justificac~ao)" VARCHAR(32), 
	"se_o_mun'icipe_faltou_sem_justificac~ao,_s'o_se_poder'a_inscrever_novamente_em" VARCHAR(10), 
	utilidade_percebida VARCHAR(32), 
	"observac~oes" VARCHAR(59)
);

CREATE TABLE acasos (
	id INTEGER NOT NULL, 
	"'ultima_data_de_atendimentos_acasos" VARCHAR(10) NOT NULL, 
	"situac~ao" VARCHAR(8), 
	local VARCHAR(13), 
	"edic~ao" VARCHAR(11) NOT NULL, 
	"observac~oes" VARCHAR(32)
);

CREATE TABLE poj (
	id INTEGER NOT NULL, 
	"'ultima_data_de_atendimento_poj" VARCHAR(10), 
	"'e_a_primeira_vez_que_se_inscreve" VARCHAR(4), 
	"c'odigo_atual" VARCHAR(7), 
	"c'odigo_antigo" VARCHAR(13), 
	"1o_opc~ao" VARCHAR(58), 
	"2o_opc~ao" VARCHAR(58), 
	"3o_opc~ao" VARCHAR(58), 
	"motivo(s)_da_candidatura" VARCHAR(264), 
	"motivo(s)_relativo(s)_ao(s)_projeto(s)_escolhido(s)" VARCHAR(269), 
	"experi^encias_consideradas_como_contributo_para_a_participac~ao_no_programa" VARCHAR(266), 
	"formac~oes_complementares" VARCHAR(237), 
	a_estudar_atualmente VARCHAR(4), 
	"em_que_hor'ario" VARCHAR(120), 
	"ingl^es" VARCHAR(9), 
	"2a_l'ingua" VARCHAR(19), 
	"2a_l'ingua___n'ivel" VARCHAR(9), 
	"3a_l'ingua" VARCHAR(18), 
	"3a_l'ingua___n'ivel" VARCHAR(10), 
	word VARCHAR(9), 
	excel VARCHAR(9), 
	powerpoint VARCHAR(9), 
	access VARCHAR(9), 
	outro_programa VARCHAR(256), 
	"outro_programa___n'ivel" VARCHAR(87), 
	"necessidades_especiais_e/ou_condic~ao_de_defici^encia" VARCHAR(4), 
	"necessidades_especiais_e/ou_condic~ao_de_defici^encia___qual" VARCHAR(8), 
	"inscric~ao_retirada_/_inv'alida" VARCHAR(4), 
	a_participar_no_programa VARCHAR(4), 
	"j'a_participou_no_programa" VARCHAR(4), 
	"inscric~ao___observacoes" VARCHAR(7), 
	entrevista___sim VARCHAR(4), 
	"entrevista___n~ao" VARCHAR(4), 
	em VARCHAR(10), 
	projeto VARCHAR(58), 
	"seleccionado/a" VARCHAR(4), 
	"seleccionado/a_em" VARCHAR(10), 
	data_de_entrada VARCHAR(10), 
	"data_de_sa'ida" VARCHAR(10), 
	"motivo_de_sa'ida___t'ermino" VARCHAR(4), 
	"motivo_de_sa'ida___outro_motivo" VARCHAR(4), 
	"motivo_de_sa'ida___outro_motivo___qual" VARCHAR(75), 
	recebeu_certificado VARCHAR(4), 
	recebeu_certificado_em VARCHAR(32), 
	"selecc~ao___observac~oes" VARCHAR(190), 
	"tutor/a" VARCHAR(32), 
	"t'ecnico/a" VARCHAR(17), 
	acompanhamento_inicial VARCHAR(4), 
	acompanhamento_inicial_em VARCHAR(10), 
	"pr'e_avaliac~ao" VARCHAR(4), 
	"pr'e_avaliac~ao_em" VARCHAR(10), 
	"1a_avaliac~ao" VARCHAR(4), 
	"1a_avaliac~ao_em" VARCHAR(10), 
	"2a_avaliac~ao" VARCHAR(4), 
	"2a_avaliac~ao_em" VARCHAR(10), 
	"3a_avaliac~ao" VARCHAR(4), 
	"3a_avaliac~ao_em" VARCHAR(10), 
	"avaliac~ao_final" VARCHAR(4), 
	"avaliac~ao_final_em" VARCHAR(10), 
	acompanhamento_em_minutos VARCHAR(5), 
	"no_de_sa'ida" VARCHAR(5), 
	utilidade_percebida VARCHAR(9), 
	"acompanhamento_observac~oes" VARCHAR(108), 
	"m'odulo_1___intelig^encia_emocional_e_trabalho_em_equipa" VARCHAR(4), 
	"m'odulo_01___de" VARCHAR(10), 
	"m'odulo_01___a" VARCHAR(10), 
	"carga_hor'aria_(de_20_horas)" VARCHAR(8), 
	"m'odulo_01___utilidade_percebida" VARCHAR(9), 
	"m'odulo_2___estrat'egias_pessoais_para_o_emprego" VARCHAR(4), 
	"m'odulo_02___de" VARCHAR(10), 
	"m'odulo_02___a" VARCHAR(10), 
	"carga_hor'aria_(de_28_horas)" VARCHAR(8), 
	"m'odulo_02___utilidade_percebida" VARCHAR(9), 
	"m'odulo_3___move_te" VARCHAR(4), 
	"m'odulo_03___de" VARCHAR(10), 
	"m'odulo_03___a" VARCHAR(10), 
	"carga_hor'aria_(de_08_horas)" VARCHAR(6), 
	"m'odulo_03___utilidade_percebida" VARCHAR(9), 
	"adequac~ao_comunicacional_e_relacional" VARCHAR(4), 
	compromisso VARCHAR(4), 
	"pr'e_poj___cumprimento_de_regras" VARCHAR(32), 
	"pr'e_poj___motivac~ao" VARCHAR(4), 
	"pr'e_poj___responsabilidade" VARCHAR(32), 
	"pr'e_poj___identificac~ao_de_servicos_e_tutores_adequados" VARCHAR(16), 
	"pr'e_poj___realizac~ao_de_experi^encias_externas_`a_cmc" VARCHAR(32), 
	"pr'e_poj___rede_de_suporte" VARCHAR(32), 
	"pr'e_poj___registos_de_acompanhamento/conte'udos_de_sess~ao" VARCHAR(32), 
	"pr'e_poj___observac~oes" VARCHAR(32), 
	"poj___adequac~ao_comunicacional_e_relacional" VARCHAR(32), 
	poj___compromisso VARCHAR(32), 
	poj___cumprimento_de_regras VARCHAR(32), 
	"poj___motivac~ao" VARCHAR(32), 
	poj___responsabilidade VARCHAR(32), 
	"poj___plano_de_transic~ao_para_a_vida_ativa" VARCHAR(32), 
	"poj___realizac~ao_de_experi^encias_externas_`a_cmc" VARCHAR(32), 
	poj___rede_de_suporte VARCHAR(32), 
	"poj___registos_de_acompanhamento/conte'udos_de_sess~ao" VARCHAR(32), 
	"poj___observac~oes" VARCHAR(32), 
	"p'os_poj___adequac~ao_comunicacional_e_relacional" VARCHAR(32), 
	"p'os_poj___compromisso" VARCHAR(32), 
	"p'os_poj___cumprimento_de_regras" VARCHAR(32), 
	"p'os_poj___motivac~ao" VARCHAR(32), 
	"p'os_poj___responsabilidade" VARCHAR(32), 
	"p'os_poj___espaco_para_registo_descritivo" VARCHAR(32), 
	"pp'os_poj___rojeto_de_vida_ativa" VARCHAR(32), 
	"p'os_poj___observac~oes" VARCHAR(32)
);

CREATE TABLE escolaridade (
	id VARCHAR(100) NOT NULL, 
	"'ultima_data_da_escolaridade" VARCHAR(19), 
	"'ultimodeescolaridade" VARCHAR(37), 
	outra___qual VARCHAR(23), 
	a_frequentar VARCHAR(81), 
	"'area" VARCHAR(262), 
	"observac~oes" VARCHAR(200)
);

CREATE TABLE situacao_face_trabalho (
	id INTEGER NOT NULL, 
	"'ultima_data_da_situac~ao_face_ao_trabalho" VARCHAR(10), 
	"situac~ao" VARCHAR(33), 
	outra___qual VARCHAR(120), 
	"observac~oes" VARCHAR(53), 
	"inscrito/a_no_ce" VARCHAR(4), 
	tempo VARCHAR(36)
);

